### ISSUE TITLE
Can't instal modul, please help me ) 

### ISSUE THREAD

**Issue by ghost** [alexander-emelyanov/yii2-articles-module#1]
./yii migrate --migrationPath=@AlexanderEmelyanov/yii/modules/articles/migrations

Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No such file or directory'

in /Users/macbookpro/www/expert.loc/vendor/yiisoft/yii2/db/Connection.php:547

Stack trace:
#0 /Users/macbookpro/www/expert.loc/vendor/yiisoft/yii2/db/Connection.php(858): yii\db\Connection->open()
#1 /Users/macbookpro/www/expert.loc/vendor/yiisoft/yii2/db/Connection.php(845): yii\db\Connection->getMasterPdo()
#2 /Users/macbookpro/www/expert.loc/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
#3 /Users/macbookpro/www/expert.loc/vendor/yiisoft/yii2/db/Command.php(834): yii\db\Command->prepare(true)
#4 /Users/macbookpro/www/expert.loc/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL)
#5 /Users/macbookpro/www/expert.loc/vendor/yiisoft/yii2/db/mysql/Schema.php(198): yii\db\Command->queryAll()
#6 /Users/macbookpro/www/expert.loc/vendor/yiisoft/yii2/db/mysql/Schema.php(97): yii\db\mysql\Schema->findColumns(Object(yii\db\TableSchema))

**Comment by alexander-emelyanov** [comment]
Another migrations are working?

**Comment by ghost** [comment]
Yes
